### ISSUE TITLE
How to run ApiGen (on Windows System)?

### ISSUE THREAD

**Issue by brunoaugusto** [ApiGen/ApiGen#888] opened 2017-06-15 15:39 UTC
I've been away of development for a very long time and since I came back I've been updating a big system I have, mostly for personal uses, and today I decided to generate its documentation.

However, I develop under Windows system. And don't fool yourselves, this doesn't make me a worse developer than a Linux user at all. In past, not sure which version but I can tell it was before ApiGen become a Composer resource (or whatever it's called) I could simply download the branch here, access the extracted folder directly through command prompt and generate the documentation by only adjusting the paths.

The documentation was generated as best as it could. If there was anything unexpected, missing or wrong with the source code parsed, a log file was generated and I cold quickly fix.

Well, I gave it a shot this new way. I installed Composer, ApiGen and tried to run. First thing I've got:

> The filename, directory name or volume label syntax is incorrect

I tried a few different path formats without success. Then I moved my command pointer directly to one level above my source directory and ran the command through there, **following the Readme.md instructions**;

> D:\bin\vendor\bin\apigen generate src myFolder --destination docs

Both directories exist and the output:

> [Symfony\Component\Console\Exception\RuntimeException]
> Too many arguments, expects arguments "command"

But now with a list of valid configuration options.

With the output list I saw that **src** is not valid. That I should use `--source myFolder` or at least `-s myFolder`

Once again, by trial and error, I adjusted and finally I saw the expected; **Scanning sources and parsing** only to receive another error few seconds later:

> Unexpected token found.

But what token? Any details about this error? Where's the log? I looked at Composer install directory, ApiGen Composer required directory, my output fodlers... Nope, *nada*

I understand how parsing works. It's really a pain and if anything goes wrong the process blows up. But differently of the very, very, very old versions, I'm sorry to say this bluntly, but it seems to be lacking some "care" with these little details.

**Comment by TomasVotruba** [comment] 2017-06-15 20:20
Hi @brunoaugusto,

thanks for detailed and very clear report. I think we can make this work.

First: are you running the version as README is? In this case `dev-master`?

**We focus on master and 5.x release only at the moment, so try it with that please.**

How to try master you'll find here: #886 (comment)

**Comment by brunoaugusto** [comment] 2017-06-16 12:03
I installed as described in the README.md, there wasn't any mention to a `dev-master`.

Well, I tried a few more things. First I changed the PHP version Composer was using. PHP 7 is "too new" and even though we can install any version we want on dedicated servers, that's not the reality in my country, but that's beside the point.

After changing the PATH Environment Variable to PHP 7 instead of PHP 5.6, because I don't see the need of Composer and similar, I don't understand them well, so after several commands trying to make it match that definition, always receiving the "satisfiable errors" the other Issue presented, I edited manually the `composer.json` to look like what posted in the Issue you linked and then I ran the update command.

A lot of files/components were installed but checking the version it was still showing me **4.1.0** instead of the 5.x, which ended up resulting in the same issue of incorrect filename/directory.

Guess I'll fallback to phpDocumentor 2 instead :(

**Comment by TomasVotruba** [comment] 2017-06-17 21:29
You are maybe using some old `apigen.phar`, that is located somewhere in your path. Try `vendor/bin/apigen` instead.

As for more info around 5.x, see: https://github.com/ApiGen/ApiGen#your-help-is-needed-to-finish-5x-release

I'd probably need more real logs (screenshots) or code (code snippets) to be able to help you better.

**Comment by brunoaugusto** [comment] 2017-06-19 11:21
I decided to clean everything, removing Composer, everything already downloaded, changing paths...

Installed/required ApiGen
`composer require apigen/apigen --dev`

Replaced Composer entry related to ApiGen with:
```
{
    "require": {
    	"apigen/apigen": "5.0.0-RC1",
    	"roave/better-reflection": "@dev"
    }
}
```
Updated dependencies
`composer update`

And then I went to check the version:

```
cd vendor\bin <enter>
apigen --version
```

I've got this:
![apigen](https://user-images.githubusercontent.com/1514089/27282844-2e796b50-54c8-11e7-801e-e34dfdff5d04.png)

Better than a catchable error, I suppose. Hope it helps solving the problem

**Comment by TomasVotruba** [comment] 2017-06-19 19:28
Thanks, awesome report!

This is caused by missed autoload in [`bin/apigen`](https://github.com/ApiGen/ApiGen/blob/f1c3b383453daf63b6d62ffe4be8c0d27e058828/bin/apigen#L11).

If you could complete [somehting like this](https://github.com/phpstan/phpstan/blob/c4a8fb0ed688171d0142d8dce98a4fa8d9506cee/bin/phpstan#L9-L22) to count on more paths, that should fix that.


```php
$possibleAutoloadPaths  [
    getcwd() . '/ven$dor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php'
];

foreach ($possibleAutoloadPaths as $possibleAutoloadPath) {
     if (file_exists($possibleAutoloadPaths)) {
        require_once($possibleAutoloadPaths);
        break;
     }
}
```

**Could you send PR if you can confirm this worked?**

**Comment by brunoaugusto** [comment] 2017-06-19 22:49
The third possible path worked, however `apigen --version` returned **Console Tool** instead of a version number, perhaps that should be looked into later.

Anyway, expanding the searchable paths I managed to run the `generate` command. I've got a few AST errors pointing a couple of silly mistakes, like a missing semi-colon, but after fixing them I've got a `ReflectionException` saying that one of my files, a custom Exception Class, doesn't exist.

I tested this file in particular, forcing this Exception to be thrown, and it worked as expected.

Any chances of the `include_path` be the issue? Because my AutoLoader, based upon [strem_context_include_path()](http://php.net/stream_resolve_include_path), faster than file_exists(), expects the root folder of loadable libraries to be appended to it.

**Comment by TomasVotruba** [comment] 2017-06-20 06:19
> The third possible path worked.

First things first. Could you please send PR for that to prevent the same issue for all other users?

As for exception, I think I know where to go.

**Comment by brunoaugusto** [comment] 2017-06-20 10:27
Unfortunately and shamefully my knowledge of GIT is restricted to personal use only. I never learned the collaborative part of it so, if you don't mind doing it yourself, I'd appreciate.

What I did was replace the `require_once` line with:

```

$possibleAutoloadPaths = [
    getcwd() . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php'
];

foreach( $possibleAutoloadPaths as $possibleAutoloadPath ) {

     if( stream_resolve_include_path( $possibleAutoloadPath ) !== FALSE ) {
        require_once( $possibleAutoloadPath ); break;
     }
}
```

**Comment by TomasVotruba** [comment] 2017-06-20 12:12
I see. I'd love to help you with that.

You actually don't need any git knowledge to do these changes. Most of small PRs I make on Github are done in browser.

When you open [`bin/apigen`](https://github.com/ApiGen/ApiGen/blob/master/bin/apigen) file in Gitbub, there is edit option:

![image](https://user-images.githubusercontent.com/924196/27332470-48d4a8fc-55c2-11e7-8cae-60c72993e710.png)
 
It might require to "fork" this repository, which can be done in browser as well.

Even if tests don't pass, you could help me to make these changes faster.

**Comment by brunoaugusto** [comment] 2017-06-20 12:18
If I knew it was that simple... Done ;)

**Comment by TomasVotruba** [comment] 2017-06-20 12:24
Wow, you're fast :)  

You've made change to your own copy of this repository. Now you need to go to [pull-requests in here](https://github.com/ApiGen/ApiGen/pulls) and there should be a "create pull-request" button to ask for adding this code here.

Just create it and I can merge it right away

**Comment by brunoaugusto** [comment] 2017-06-20 13:10
Done ;)

**Comment by TomasVotruba** [comment] 2017-06-20 14:03
Thank you :)

**Comment by TomasVotruba** [comment] 2017-06-20 14:06
As for `apigen --version`. ApiGen uses `Symfony\Console`, that doesn't show any version if not set manually.

It displays the default name: "Console Tool", because none is set.

There is nice discussion about this: https://github.com/phpstan/phpstan/issues/160#issuecomment-301338992

**We could add "ApiGen" name and  "Unknown version" to make this clear**: https://github.com/phpstan/phpstan/commit/49d8ac12cfa81daaaa57fe5f89c937a6cc3f1317

What do you think?

**Comment by brunoaugusto** [comment] 2017-06-20 14:17
If you're like me and don't have patience to increment the build version, like in 5.0.1.12345, after every single tiny change you make, that shouldn't be a problem.

What about that `ReflectionException`? Found the culprit?

**Comment by TomasVotruba** [comment] 2017-06-20 17:13
Could you create a test for that?

Here are instructions: https://github.com/ApiGen/ApiGen/issues/890#issuecomment-309545672

And here PR example: https://github.com/ApiGen/ApiGen/pull/891

**Comment by TomasVotruba** [comment] 2017-06-20 17:16
As for "version", could you add those 2 arguments I talked about: https://github.com/ApiGen/ApiGen/blob/master/src/config/services.yml#L40

This is simpler to start with

**Comment by brunoaugusto** [comment] 2017-06-20 21:05
I'm really doing this by trial and error. It's MUCH different of my usual workflow since I don't use Symfony and currently my components are manually tested, individually, as I develop them.

Anyway... I created the class like you said:

```
<?php declare(strict_types=1);

namespace ApiGen\Tests\Generator;

use ApiGen\Generator\ClassGenerator;
use ApiGen\Reflection\Parser\Parser;
use ApiGen\Tests\AbstractContainerAwareTestCase;

final class ClassExistenceTest extends AbstractContainerAwareTestCase
{
    /**
     * @var ClassGenerator
     */
    private $classElementGenerator;

    protected function setUp(): void
    {
        /** @var Parser $parser */
        $parser = $this->container->get(Parser::class);
        $parser->parseDirectories([__DIR__ . '../next']);

        $this->classElementGenerator = $this->container->get(ClassGenerator::class);
    }

    public function testGenerate(): void
    {
        $this->classElementGenerator->generate();

        $this->assertFileExists(
            TEMP_DIR . '/Components/Decorators/DecoratorException.php'
        );
    }
}
```

However setting the path to `/Sources` from where the class is located would be a huge burden because the class mentioned by the previous `ReflectionException` is a children of a very complex class with several dependencies so, instead, I used a level above in there (`../next`).

I ran the `generate` command over that class, happy to see the progress bar running, only to get a different error (ง ͠° ͟ل͜ ͡°)ง

![apigen](https://user-images.githubusercontent.com/1514089/27354205-2d29f39e-55dd-11e7-986d-170d22a6210a.png)

I don't know how it works in ApiGen's context but in my development this surely wouldn't work because `AbstractContainerAwareTestCase` is not being resolved to anything, even with this "enhanced" AutoLoader. In fact, I've searched among all files Composer downloaded and I didn't even find a a class with that name. o.O

---

Allow me do an extended parenthesis here

While sniffing around the source files, I've seen a bunch of `__DIR__` and `getcwd()` at deeper levels of the filesystem. Personally I think this is a bad idea, specially if you Application can also run in Windows systems.

If worth the suggestion, you could add the starting point of your classes to the *include_path* and call your classes always forward instead backwards, from a deep level based with *current working directory*. This could possibly allow you to not have "possible candidate paths" anymore because wherever the User installed ApiGen it would work because it wouldn't be needed to "guess" anything.

Let me show you a very basic skeleton of my Applications to illustrate:

```
set_include_path(
    '.' . PATH_SEPARATOR . realpath( './common' )
);

require_once 'Next/Loader/AutoLoader.php';
require_once 'Next/Loader/AutoLoader/Stream.php';

$autoloader = new Next\Loader\AutoLoader;
$autoloader -> registerAutoloader( new Next\Loader\AutoLoader\Stream );

Next\Components\Debug\Handlers::register( 'exception' );
Next\Components\Debug\Handlers::register( 'error' );
```

> If you want to check the codes themselves you can start from[here](https://github.com/nextframework/next)

All classes common to all Applications go in this very suggestive `common` directory. Because it's a very simple `./`, `realpath()` hardly (or never) fails on Windows/Linux (can't say about Mac >.<) and then every call, to every resource, go always forward, deeper into the filesystem.

And, as far as I know, you don't have to worry about any CLI caveats. In fact, I don't use a full webserver myself these days. Almost the whole code (because of the huge hiatus in development I took) of that link above runs perfectly with just the built-in webserver.

**Comment by TomasVotruba** [comment] 2017-06-21 13:13
I've added `--version` info in commit: https://github.com/ApiGen/ApiGen/commit/64c2570caaf59f5581e90ddf8cc35d64f799d6a2

> 

> Allow me do an extended parenthesis here

Please open a new issue for that. It's getting crowded here.
From scanning the text: we support Composer to autoload classes. Why don't you use that?

**Comment by TomasVotruba** [comment] 2017-06-21 13:15
Closing, since 1st issue was succesfuly resolved.

**Closed** 2017-06-21 13:15 UTC
