### ISSUE TITLE
Value definition is empty

### ISSUE THREAD

**Issue by FlTr** [ApiGen/ApiGen#576] opened 2015-03-24 21:22 UTC
```
> apigen generate --debug
Scanning sources and parsing

Value definition is empty.
```

Don't know how to interpret this message (v4.0.0)

**Comment by TomasVotruba** [comment] 2015-03-25 17:07
Could you show me your `apigen.neon`?

**Comment by FlTr** [comment] 2015-03-26 20:02
Of course:
```
extensions: [php]
source: [./web/backend]
destination: api/php
charset: [UTF-8]
main: lti
title: LTI Backend API
baseUrl: http://example.org/lti/api/
templateTheme: bootstrap
groups: auto
accessLevels: [public, protected, private]
php: false
sourceCode: true
tree: true
deprecated: true
todo: true
download: false
```

**Comment by TomasVotruba** [comment] 2015-04-04 14:36
I guess this is related to the code. Could you please identify the specific `*.php` file that is causing this?

**Comment by TomasVotruba** [comment] 2015-05-24 01:33
Ping @FlTr

**Comment by TomasVotruba** [comment] 2015-05-24 01:48
Also ApiGen version please.

**Comment by FlTr** [comment] 2015-05-25 20:57
Sorry for late answer. Version was 4.0, i think. Also i think you're right with your guess. There was a method with just a 
```php
/**
 *
 */
```
-block in front of it. As far as i remember, deleting it or fill in some characters was the solution.

**Comment by TomasVotruba** [comment] 2015-05-26 10:56
Yea, empty blocks have no use.
Maybe improving exception message would help, if you find it. It might be located in [PHPTokenReflection](https://github.com/Andrewsville/PHP-Token-Reflection)

Closing then.

**Closed** 2015-05-26 10:56 UTC

**Comment by nichtich** [comment] 2016-01-29 19:44
I'd reopen until fixed with a better exception message.

**Comment by kix** [comment] 2016-03-28 20:51
Confirmed, looks like I've stumbled upon the same issue and I don't really have any empty comment blocks.

**Comment by mihaikelemen** [comment] 2016-06-22 06:48
The same for me (using version 4.1)

**Comment by populov** [comment] 2016-10-15 17:57
In my case, looks like this error is caused by constant array declaration:
```php
const MYARRAY = [0, 2, 5];
```

**Comment by juvenn** [comment] 2016-11-18 04:23
I can also confirm @populov's case,  a constant with array will cause problem.

**Comment by adamcornforth** [comment] 2016-11-28 16:27
+1 @populov, a constant array in my project caused this problem too. 

Editing my `apigen.conf` to exclude the file with the constant array fixed the problem, e.g:

```
exclude: 
    - 'ClassWithConstantArray.php'
```

**Comment by nelson6e65** [comment] 2016-12-13 09:48
> @populov:
> In my case, looks like this error is caused by constant array declaration
:+1:

@TomasVotruba I'm still having this issue too, caused by an array `const`.  Why is this closed? 

ApiGen: `4.1.0`
PHP: `5.6.28`

**Comment by kurinniy** [comment] 2017-01-14 12:53
I confirm this problem with array `const`

PHP 5.6.27
ApiGen 4.1.0

File that causes problem looks like this:

```
<?php

namespace Direct;

class Constants
{
	const CLIENT_PREFIX = 'zzcli';

	const CAMPAIGN_PREFIXES = ["asdf", "zxcv", "qwer"];
}
```

**Comment by ek9** [comment] 2017-03-27 06:53
For anyone stumbling upon this issue, the support for this will be implemented as part of #774 issue.
