### ISSUE TITLE
Unexpected token found (debug mode does not work)

### ISSUE THREAD

**Issue by enumag** [ApiGen/ApiGen#642] opened 2015-09-03 09:01 UTC
Hi, I'm trying to generate api documentation for my project so I created an apigen.neon file and installed apigen. For some reason though every time I run `apigen generate` I end up with this:

```
Scanning sources and parsing

Unexpected token found.
```

So I searched a little and `--debug` option is supposed to give me some more information about the error. However `apigen generate --debug` returns the same output as the original command. No new information whatsoever.

I tried both the stable 4.1 version and current 4.2-dev with the same result.

Is the debug option broken or something?

**Comment by enumag** [comment] 2015-09-03 09:11
My apigen.neon file:

```
source:
	- app/src
	- libs/src
	- vendor

destination: api
```

If I remove vendor it Apigen fails with `Could not determine ... relative path` so apparently #465 is not entirely fixed (I'm using windows). Of course debug mode still does not work so I have no more information to provide about this error either.

**Comment by enumag** [comment] 2015-09-03 11:02
Ok so the debug mode doesn't do anything because the exception is caught in `ApiGen\Console\Command\GenerateCommand::execute()`. What is the purpose of debug mode then?

As for relative path I hotfixed it by adding `$fileName = str_replace('\\', '/', $fileName);` to the beginning of `ApiGen\Generator\Resolvers\RelativePathResolver::getRelativePath()`. Not sure if it's the proper fix so I won't send a PR:

Finally the `Unexpected token found.` is caused by the old library https://github.com/Andrewsville/PHP-Token-Reflection and some PHP 5.6 syntax. Apparently there is new library https://github.com/ApiGen/ElementReflection which is meant to replace it but the work is not finished and seems abandoned. :-(

**Comment by ellier** [comment] 2016-03-30 16:52
Same problem here.

**Comment by shambhukumar** [comment] 2016-07-08 06:53
Solve : Find in your code does have any "# some code " remove

class Reports
{
	public function getSessionsbyDateRange($value='')
	{
		# code...
	}

	public function ($value='')
	{
		# code...
	}
}

**Comment by netbrothers-tr** [comment] 2016-08-08 09:55
Is there any progress on this issue? Does anyone of you have an idea on how to get some useful info on where the script fails? Because of the missing debug output I cannot, well, debug. ;-)

@shambhukumar: Those two pitfalls you mentioned are surely to watch out for, but they probably aren't the only things that cause this problem.

**Comment by netbrothers-tr** [comment] 2016-09-07 21:49
Hi @POPSuL,

> '#' style comments is works properly!

this is just one case in which the error occurs. There are others (using [double column class](https://laracasts.com/discuss/channels/tips/double-colon-class) `::class` for instance).

Hence, I can't see why this issue could be considered fixed, but maybe it can be marked as a duplicate of or referenced by another issue?

**Comment by bgaillard** [comment] 2016-11-01 19:56
Hi, the same problems appears when the source code is in PHP7 and return types are used. 

For example this works.

```
public function fetch(array $filters = []) {}
```

But this does not and simply displays `Unexpected token found.` even with the `--debug` option.

```
public function fetch(array $filters = []) : array {}
```

I think most of errors are linked to bad PHP7 support, this is linked to the following issues.

* https://github.com/ApiGen/ApiGen/issues/763
* https://github.com/ApiGen/ApiGen/issues/745
* https://github.com/ApiGen/ApiGen/issues/680
* https://github.com/ApiGen/ApiGen/issues/635

**Comment by skyzyx** [comment] 2016-11-15 00:28
Same here. Writing code for PHP 7.

**Comment by RikudouSage** [comment] 2016-11-18 10:01
I still have this problem, the code is in PHP 5.6 and I don't know what could cause this error. The only thing that comes to my mind is the mentioned ::class usage.

**Comment by netbrothers-tr** [comment] 2016-11-18 14:25
I love ApiGen but at the moment I can't use it because of this issue. PHP 5.6 is  now widely adopted and people are switching to PHP 7 already. Anything before PHP 5.6 is being considered **end of life** (see [here](http://php.net/supported-versions.php)). Is there any progress?

**Comment by jankal** [comment] 2017-03-11 21:51
This could also be related to type-hinting the new [variable-arg-list](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) with `function xyz(array ...$tests) {}` which actually seems valid.

**Comment by TomasVotruba** [comment] 2017-03-16 17:11
Related to the original issue: I've removed all exception hiding mechanism, so in next version every exception will be seen nice and clear.

https://github.com/ApiGen/ApiGen/pull/811/commits/edd2890408e6ffcaaf7e51e32cf8295c56e5018c

**Closed** 2017-03-16 17:11 UTC
Labels: due-to-tokenreflection

**Comment by enumag** [comment] 2017-03-19 09:31
@TomasVotruba Awesome!

**Comment by vitalygoji** [comment] 2018-01-02 23:26
apigen php "unexpected token found"
Can someone recommend alternative tool?

**Comment by vlastavesely** [comment] 2018-01-04 08:33
Are you sure that you use `apigen 5.0.0` and not version 4?

**Comment by pifou25** [comment] 2020-11-22 17:42
how do you update to apigen v5? the default install or compose is always 4, seems that github branches only related to 4.x version
