### ISSUE TITLE
Reflection: Unimplemented methods

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#894] opened 2017-06-21 14:09 UTC
I've found another problem.

In `ApiGen\Reflection\Reflection\Trait_\TraitMethodReflection` there are unimplemented methods. Particularily, I've got this exception:

```
[ApiGen\Exception\Templating\FailedRenderFileException]                      
Rendering of "......./vendor/apigen/apigen/packages/ModularConfiguration/src/Option/../../../../packages/ThemeDefault/src/class.latte" template to "...../class-test.html" file failed due to: Return value of ApiGen\Reflection\Reflection\Trait_\TraitMethodReflection::isDeprecated() must be of the type boolean, none returned 
```

It is logic for the function `TraitMethodReflection::isDeprecated()` has strict typehint. But, what is strange, I am getting this error only when I am generating docs by running `apigen generate`. When I run `phpunit`, it generates documentation without fail. I even tried to edit file `/packages/ThemeDefault/src/class.latte` to see whether the condition `n:class="$ownTrait->isDeprecated() ? deprecated"` is not skipped and it wasn't.

So, where problem lies is obvious: in unimplemented methods.

But why test passes? It seems to me like the strict typing is ignored somehow. I do not know :)

**Comment by niallcusack** [comment] 2017-06-21 14:47
Hi,

I've just come across what I think is the same issue while running ApiGen against Laravel 5.4.27 . Similarly the issue appears to only affect classes with defined traits. 

<pre>Rendering of \vendor\apigen\apigen\packages\ModularConfiguration\src\Option/../../../../packages/ThemeDefault/src\class.latte" template to "\docs\class-App.Http.Controllers.Controller.html" file
  failed due to: Argument for filter "linkReflection" has to be type of "ApiGen\Reflection\Contract\Reflection\AbstractReflectionInterface". "string" given.</pre>

If it's any help, the PHP version is 7.1.6.

Thanks

**Comment by TomasVotruba** [comment] 2017-06-22 11:31
Great catch!

I think it's caused by `TraitMethodReflection` and not `TraitReflection`.

**Comment by TomasVotruba** [comment] 2017-06-22 11:34
@vlastavesely You could extend your test with property and method: https://github.com/ApiGen/ApiGen/commit/2a973c973eabf9474c115fed7bcccd84b151e20a#diff-02318106887b51ead60f6451bf74e5daR5

It should fail then. If not, I will confirm the weirdness :D 

Also, you can complete those unimplemented methods based on [`ClassMethodReflection`](https://github.com/ApiGen/ApiGen/blob/64c2570caaf59f5581e90ddf8cc35d64f799d6a2/packages/Reflection/src/Reflection/Class_/ClassMethodReflection.php#L68-L76)

**Comment by TomasVotruba** [comment] 2017-06-22 11:36
@niallcusack This has already been fixed in the master, see: https://github.com/ApiGen/ApiGen/issues/890#issue-236830148

**Comment by vlastavesely** [comment] 2017-06-22 11:45
I am going to look on that. :)

**Comment by TomasVotruba** [comment] 2017-06-22 17:16
Thank you :)

**Closed** 2017-06-23 14:29 UTC
