### ISSUE TITLE
Unexpected token found when encountering PHP 5.5 construct type::class

### ISSUE THREAD

**Issue by crazycodr** [ApiGen/ApiGen#680] opened 2015-11-13 13:44 UTC
I just ran APIGen on our legacy code and got an `Unexpected token found` with no debug message. No big deal though, i just ran api gen in smaller units until i found out that it's not the legacy code that crashed the tokenizer but some new PHP 5.5 code such as:

```
$ioc->bind(
    \LearningBird\Email\Review\ReviewEmailSourceInterface::class,
    \LearningBird\Email\Review\DatabaseReviewEmailSource::class
);
```

So i can fix this pretty easily by reverting back to a string based representation of the class name which i don't like, but if it's a temporary fix, i'll take it.

I hope you can fix this asap as this is getting a more and more used construct.

Thanks

**Comment by enumag** [comment] 2016-03-07 21:14
Probably duplicate of #642. The important part form that issue is this:

Finally the Unexpected token found. is caused by the old library https://github.com/Andrewsville/PHP-Token-Reflection and some PHP 5.5 syntax (really 5.5, not 5.6, I've double checked that). Apparently there is new library https://github.com/ApiGen/ElementReflection which is meant to replace it but the work is not finished and seems abandoned. :-(

**Comment by cisso** [comment] 2016-05-21 15:52
There's a [fork of PHP-Token-Refelction](https://github.com/kornrunner/PHP-Token-Reflection) that might be worth considering as a drop-in replacement.
One catch: While it had been developed until recently [the maintainer unfortunately mentioned](https://twitter.com/mootari/status/733749976891822081) that he plans to discontinue further development.

**Comment by lisachenko** [comment] 2016-10-26 15:49
Hi, you can try to switch to the [goaop/parser-reflection](https://github.com/goaop/parser-reflection) which supports PHP5.6 and PHP7.0 features and provides native Reflection API.

**Comment by sidyll** [comment] 2017-05-22 16:04
Is there any solution to this? I just installed apigen, which looks fantastic, but with this error it is unusable. Modifying code to remove `::class` is not an option...

**Closed** 2017-06-02 16:23 UTC
Labels: due-to-tokenreflection, enhancement
