### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by vietnguyen010** [ApiGen/ApiGen#1001] opened 2017-09-07 10:11 UTC
I follow your document to install ApiGen like so

	composer require apigen/apigen --dev                                                                    

I run under command to generate docs, which my project is Laravel 5.4

    λ vendor\bin\apigen generate --source D:\Work\project\app --exclude=*/commands/*,*/config/*,*/database/*,*/lang/*,*/start/*,*/storage/*,*/views/*,filters.php,routes.php,web.php,api.php --destination api --no-source-code

An error has appeared

`Imported namespace name could not be determined.`

Then I know need to using 5x version, so I keep following your tutorial to update composer.

	{
		"require": {
			"apigen/apigen": "5.0.0-RC5",
			"roave/better-reflection": "dev-master#a402048"
		}
	}

And run command to update `composer update` but then I got this dead end.

	λ composer update                                                                                                                        
	Loading composer repositories with package information                                                                                   
	Updating dependencies (including require-dev)                                                                                            
	Your requirements could not be resolved to an installable set of packages.                                                               
																																			 
	  Problem 1                                                                                                                              
		- Installation request for apigen/apigen 5.0.0-RC5 -> satisfiable by apigen/apigen[v5.0.0-RC5].                                      
		- apigen/apigen v5.0.0-RC5 requires phpdocumentor/reflection-docblock ^3.1 -> satisfiable by phpdocumentor/reflection-docblock[3.1.0,
	 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3].                                                                                                     
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.1.0].                                                          
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.1.1].                                                          
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.0].                                                          
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.1].                                                          
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.2].                                                          
		- Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.3].                                                          
		- roave/better-reflection dev-master requires phpdocumentor/reflection-docblock ^4.1.1 -> satisfiable by phpdocumentor/reflection-doc
	block[4.1.1].                                                                                                                            
		- Installation request for roave/better-reflection dev-master#a402048 -> satisfiable by roave/better-reflection[dev-master].

So what can I do now?

**Comment by vlastavesely** [comment] 2017-09-07 10:26
Duplicate of #1000

**Closed** 2017-09-07 13:08 UTC
