### ISSUE TITLE
highlighted source code should not be duplicated for every function

### ISSUE THREAD

**Issue by fschlich** [ApiGen/ApiGen#717] opened 2016-04-20 21:40 UTC
For functions outside a class, ApiGen generates a separate source-function-FOO.html file for every single function, as well as a source-class-FOO.html file, although it knows that they all come from the same source file (the link says "Located at foo_stuff.php"). This can lead to MANY files with 100% identical content.

Can we have a single source-foo_stuff.php.html file instead, that is linked to from all places, please?

**Comment by jadb** [comment] 2016-08-16 04:50
Sorry for the delay.

You have some valid points right there but I haven't given it much thought. Do you want to give it a try?

**Comment by TomasVotruba** [comment] 2017-03-17 17:11
So every non-classical function is considered like class?

**Comment by TomasVotruba** [comment] 2017-04-01 03:39
Closing for no feedback.

If still an issue, could you send failing test for this?

**Comment by ek9** [comment] 2017-04-02 22:16
I believe we can reopen this as this would be a general improvement for large-codebases (instead of generating multiple files, we could get away with only doing it once). While this is not a bug, it might be a nice enchancement in the future. I'll reopen and poke around this in the future.

**Comment by TomasVotruba** [comment] 2017-04-02 22:38
I agree with you. Still, provide a failing test please. Without it, I can't fix it.

**Comment by ek9** [comment] 2017-04-03 01:14
Will do so, I've marked them with `need-info` label (I'll make a more sutable `tests-required` later) and unassigned it from `5.x` milestone so it's not in the way until we got all the info and tests covered.

**Comment by TomasVotruba** [comment] 2017-04-03 01:36
Awesome, thank you

**Comment by TomasVotruba** [comment] 2017-06-02 09:53
I get it now :+1:

**Closed** 2017-06-02 10:30 UTC
Labels: need-tests
