### ISSUE TITLE
APIGen can not resolve prase PHP 7  return type declare

### ISSUE THREAD

**Issue by netroby** [ApiGen/ApiGen#766] opened 2016-12-23 03:23 UTC
If our code contains PHP 7 return type declare , like 

```php

class test {
    public function demoAction() : string {
         ...
    }
}
```
The apigen will failed with following message:
```bash
Scanning sources and parsing

Unexpected token found.
```

**Comment by gustavonecore** [comment] 2017-01-23 19:52
What's the status of this issue, is there some experimental branch or a release about it?

**Comment by StephanKrauss** [comment] 2017-02-21 08:19
Hello,

I have the same problem.
For the new projects, I can no longer use Apigen.

**Comment by jankal** [comment] 2017-03-11 21:08
This issue is closely related to #635. Please keep patient.

**Comment by ek9** [comment] 2017-04-04 01:35
Closing this as it's a duplicate of #745

**Closed by ek9** 2017-04-04 01:35 UTC
Labels: due-to-tokenreflection, PHP 7
